Task 18
kirster/test-guru pull request #19
Opened 2018-01-14 12:48 UTC by kirster

2018-01-15 00:18 UTC, psylone requested changes

2018-01-15 00:18 UTC, psylone commented on app/views/test_passages/result.html.erb
> +  <%= result_output(@test_passage) %>
Нехорошо что размазывается логика того пройден ли тест между хэлпером и представлением. Я понимаю почему здесь такая реализация, тем не менее, хочется видеть знание о результате прохождения теста в единственном месте.

2018-01-15 00:18 UTC, psylone commented on app/assets/javascripts/utilities/timer.js
> +  setInterval(function() {
Я могу отключить в браузере JS и проходить тест сколько захочется. Что будет когда я дойду до последнего вопроса? Приложение скажет мне о том что время вышло?

2018-01-15 00:19 UTC, psylone commented on app/assets/javascripts/utilities/timer.js
> +  setInterval(function() {
Даже если не отключать JS, я могу поставить брэйкпоинт и изменить значение времени в HTML атрибуте до того как запустится `setInterval`.

2018-01-15 00:23 UTC, psylone commented on app/assets/javascripts/utilities/timer.js
> +  setInterval(function() {
Или вообще переопределить функцию `elapseTime`.

2018-01-15 06:23 UTC, kirster commented on app/assets/javascripts/utilities/timer.js
> +  setInterval(function() {
Единственная идея у меня - оставить код в timer.js, а в контроллер test_passages добавить ,например, коллбэк before_action на update, который будет сравнивать текущее время и время окончания, сохраненное в сессию. Других вариантов, если честно, не вижу

2018-01-15 15:19 UTC, psylone commented on app/assets/javascripts/utilities/timer.js
> +  setInterval(function() {
Этой подойдёт. Можно ещё в модель `TestPassage` класть атрибут со временем окончания теста (если таймер установлен).

2018-01-15 23:25 UTC, psylone requested changes

2018-01-15 23:25 UTC, psylone commented on app/helpers/test_passages_helper.rb
> +    session[passage_id.to_sym] ||= Time.now + test_passage.test.timer.minutes
Объекту `session` без разницы что передаётся в качестве аргумента метода `[]` символ или строка.

2018-01-15 23:25 UTC, psylone commented on app/helpers/test_passages_helper.rb
> +    session[passage_id.to_sym] ||= Time.now + test_passage.test.timer.minutes
Лучше использовать `Time.current` вместо `Time.now` чтобы учитывать сконфигурированный часовой пояс приложения.

2018-01-15 23:25 UTC, psylone commented on app/helpers/test_passages_helper.rb
> +    session[passage_id.to_sym] ||= Time.now + test_passage.test.timer.minutes
Можно ещё использовать `test_passage.test.timer.minutes.from_now`.

2018-01-15 23:25 UTC, psylone commented on app/views/shared/_timer.html.erb
> +<div class="timer" data-end-time= "<%= passage_end_time(@test_passage) %>"
Нехорошо что хэлпер отвечает за установку значения сессии. Хэлпер - это обычно метод который как-то подготавливает данные для представления. В более расширенной модели используются специальные объекты - _form objects_ вместо хэлперов. Например, есть вот такой интересный проект: http://trailblazer.to/gems/cells/.

Так или иначе, лучше данные сессии выставлять в контроллере.

2018-01-15 23:25 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +    if Time.now >= session["passage_#{@test_passage.id}".to_sym]
Проверь пожалуйста случай когда у теста не установлен таймер.

2018-01-16 23:11 UTC, psylone approved these changes

2018-01-16 23:11 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +    if @test_passage.test.timer
Лучше обойтись одним `if`-ом и сделать в модели метод, например: `if @test_passage.stale?(session)`.

2018-01-16 23:11 UTC, psylone commented on app/controllers/tests_controller.rb
> +      session["passage_#{current_user.test_passages.last.id}"] = @test.timer.minutes.from_now
Лучше использовать один и тот же интерфейс: `current_user.test_passage(@test)`.

2018-01-16 23:11 UTC, psylone commented on app/controllers/tests_controller.rb
> +    session["test_#{@test.id}"] ||= @test.questions.count
Не стоит использовать сессию в качестве кэша. Если нужен кэш лучше использовать [`Rails.cache`](http://guides.rubyonrails.org/caching_with_rails.html#low-level-caching). Всё таки в сессии данные гоняются туда-сюда с каждым запросом, поскольку по умолчанию сессия хранится в куках.

2018-01-16 23:11 UTC, psylone commented on app/controllers/tests_controller.rb
> +    session["test_#{@test.id}"] ||= @test.questions.count
Кроме того, человек может начать проходить тест и не пройти его. Потом админ может отредактировать этот тест, поменяв количество вопросов.

2018-01-16 23:11 UTC, psylone commented on app/controllers/tests_controller.rb
> +    session["test_#{@test.id}"] ||= @test.questions.count
Я бы и для таймера хранил значение в модели `TestPassage` вместо сессии.

2018-01-17 07:37 UTC, merged